spring:
#   redis:
#     host: 172.17.0.1
#     #assword: 123456
#     port: 6379
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/dataopen
      username: root
      password: gs963852
  application:
    name: springcloud-provider-config
  profiles:
    active: csdn
logging:
  level:
    root: info
    org.hibernate : info
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    pri.zxw.spring_base : debug
server:
  port: 8100